apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wh12b8k6k-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wh12b8k6k-go 
  name: wh12b8k6k-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wh12b8k6k-go 
